version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: golang:1.19
    environment:
      GOPATH: /go
    steps:
      - checkout
      - run:
          name: RUN UNIT TEST
          environment:
            GO111MODULE: "on"
          command: bash scripts/deploy.sh release v0.1.0
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          context: develop
