version: 2.1
orbs:
  goreleaser: hubci/goreleaser@2.1.0
commands:
  install:
    description: |
      Install GoReleaser in a job. This command supports Linux and macOS on both amd64 and arm64. Installs to ~/bin.
    parameters:
      version:
        description: The GoReleaser version. This is a full SemVer version.
        type: string
    steps:
      - ci/init
      - run:
          name: "Install GoReleaser"
          command: |
            # Ensures the directory we need exist.
            # Assuming this path is in PATH should move to hubci/sphere at some point.
            mkdir -p ~/bin

            # Get the CPU arch. This will also move to hubci/sphere in the future
            cpuArch=$( uname -m )

            # set the OS name for the asset URL
            case $OSD_FAMILY in
              linux)
                osName="Linux"
                installPath=~/bin
                ;;
              darwin)
                osName="Darwin"
                # this is done because CCI mac images don't have ~/bin in PATH
                installPath=/usr/local/bin
                ;;
              *)
                echo "Unsupported Operating System"
                exit 1
                ;;
            esac

            dlURL="https://github.com/goreleaser/goreleaser/releases/download/v<<parameters.version>>/goreleaser_${osName}_${cpuArch}.tar.gz"
            curl -sSL $dlURL | $SUDO tar -xz -C ${installPath} goreleaser
jobs:
  build:
    working_directory: /go/src/github.com/ghdwlsgur/govpn
    docker:
      - image: golang:1.19
    environment:
      GOPATH: /go
    steps:
      - checkout
      - run:
          name: RUN UNIT TEST
          environment:
            GO111MODULE: "on"
          command: bash scripts/deploy.sh release_test
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          context: develop
